### ISSUE TITLE
Feature request: add support for command with ':'

### ISSUE THREAD

**Issue by havenchyk** [bahmutov/npm-quick-run#24]
Hi, @bahmutov, thanks for you amazing work!

I frequently use scripts like `"watch:test": "npm run test -- --watch"`, that contain `:` in the name.
So the idea to support `nr w:t`

What do you think? I guess it can be done as an extension of [json-package](https://github.com/bahmutov/json-package/blob/master/src/json-package.js), isn't it?

**Comment by bahmutov** [comment]
interesting idea, I don't use the ":" in my script names, but definitely see the value in your case. Have you looked at the code for finding scripts in json-package? If you can implement it (with tests) in json-package, I promise to quickly merge it and bump `npm-quick-run` to have this.

**Comment by havenchyk** [comment]
thanks for a quick response! I've looked through the method, actually I'll try to find time to implement it with tests.

**Comment by kentcdodds** [comment]
[I also would love this](https://twitter.com/kentcdodds/status/904900505305980929) :smile:

Maybe someday I'll find time to work on it 🙃

**Comment by kentcdodds** [comment]
Actually, I think what would be best is if the scripts were sorted via [match-sorter](https://github.com/kentcdodds/match-sorter). Would you be willing to accept a PR that does that?

**Comment by bahmutov** [comment]
Of course @kentcdodds - everything will be merged quickly :)

**Comment by lordlycastle** [comment]
![...merged quickly](https://media.giphy.com/media/1l7GT4n3CGTzW/giphy.gif)

So life took over.... happens to all the adults. Was this ready or started? I would take it over.

And I also want to add fuzzy search since prefix isn't good enough for us as we have variations using : `command, command-fix, command-framework, command:beta, etc.` What do you think @bahmutov

**Comment by bahmutov** [comment]
Well, I am on board, but no one has opened a pull request, so ...

**Comment by sinnbeck** [comment]
Shouldnt this fix just run if there is an exact match? Currently it does not

![image](https://user-images.githubusercontent.com/13980140/111117930-73c02f80-8568-11eb-8ccd-3619b4d57b26.png)
