### ISSUE TITLE
Add fuzzy search along with of prefix

### ISSUE THREAD

**Issue by lordlycastle** [bahmutov/npm-quick-run#32]
Prefix is good but not when you have long `command, command:fix, command:beta, command:dev` then it fails. 

So I wish to add fuzzy search; many JS library already implement it.

**Comment by lordlycastle** [comment]
@bahmutov  there's already `fuzzy` package as dependency.... is that used for something?

**Comment by lordlycastle** [comment]
### Dependencies:
<img width="400" alt="SS 2020-07-29 at 11 16 30" src="https://user-images.githubusercontent.com/11729541/88781666-f5f01500-d18c-11ea-877c-eec71d441561.png">

**Comment by bahmutov** [comment]
Done and released, if you have `command, command:fix, command:beta, command:dev` you could use

`nr c-f` to run `command:fix` for example. I will need to invent something to be able to run `command` by itself

**Comment by lordlycastle** [comment]
Thank you so much!

I love this tool. Without it yarn/npm isn’t complete IMO.
